"""empty message

Revision ID: 916526fbce4d
Revises: 
Create Date: 2024-10-31 22:46:11.417277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916526fbce4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_coins')
    op.drop_table('coins_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins_details',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=100), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('added', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sa.VARCHAR(length=800), nullable=True),
    sa.Column('homepage', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all_coins',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=100), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('added', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_shit', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
