from backend.scrappers.btc_talk.btc_talk import BtcTalk
from backend.scrappers.coingecko.coingecko import Coingecko
from backend.scrappers.exchanges.xeggex import Xeggex
from backend.scrappers.exchanges.tradeogre import Tradeogre
from backend.scrappers.pools.coinfoundry import CoinFoundry
from backend.scrappers.pools.f2pool import F2pool
from backend.scrappers.pools.miningpoolstats import MiningPoolStats
from backend.scrappers.pools.rplant_xyz import Rplant
from backend.scrappers.pools.twominers import TwoMiners
