name: Lint

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest  # Only run on Linux

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Lint with ruff
      run: |
        ruff check